ALTER TABLE HIV_Project
MODIFY COLUMN Year INT NULL,
MODIFY COLUMN People_with_HIV INT NULL,
MODIFY COLUMN HIV_Death INT NULL,
MODIFY COLUMN Women_with_HIV_older_than_15 INT NULL,
MODIFY COLUMN P_woment_with_HIV_ARVs_PMTCT FLOAT NULL,
MODIFY COLUMN HIV_p_women_babies_tested_HIV_within_2_months FLOAT NULL,
MODIFY COLUMN Population INT NULL;
